### ISSUE TITLE
Compatibility with vue/sort-keys linting rule

### ISSUE THREAD

**Issue by skattabrain** [kaidjohnson/redux-connect-vue#93]
The Vue eslint team recently introduced a new "vue/sort-keys" rule - https://eslint.vuejs.org/rules/sort-keys.html 

This rule can be used in place of eslint's `sort-keys` rule as it allows the component's top properties to remain in the style guide recommended/desired sort order (https://eslint.vuejs.org/rules/order-in-components.html) while allowing child property sort order to be enforced alphabetically. Previously `vue/order-in-components` and `sort-keys` where not compatible.

The trouble I'm having is getting the linter to recognize the default export where it's a function returning the object.

```
export default connect(state, actions)({
	components,
	data,
	computed,
	created,
	methods
});
```

In this example, the linter is applying `sort-keys` without regard to `order-in-components` and flagging `data` as needing to come after `created`.

**Comment by kaidjohnson** [comment]
It's been a long time coming, but I'm introducing version 2, which leverages the composition API for this functionality. The `connect()` wrapper has been removed in favor of `useState` and `useActions` within `setup()`. v2 is intended to be used with Vue 2.x and https://github.com/vuejs/composition-api/tree/v3.0.0-beta.0

A v3 release is in the works as well, which will support Vue 3
